---
deployment:
  tasks:
    - export DEPLOYPATH=/home/pine24441130/public_html/
    - /bin/cp -R admin $DEPLOYPATH
    - /bin/cp -R home $DEPLOYPATH
    - /bin/cp -R includes $DEPLOYPATH
    - /bin/cp -R signup $DEPLOYPATH
    - /bin/cp -R login $DEPLOYPATH
    - /bin/cp -R contact.php $DEPLOYPATH
    - /bin/cp -R plans.php $DEPLOYPATH
    - /bin/cp -R index.php $DEPLOYPATH